Trying another approach.

diff --git a/.github/workflows/build_documentation.yml b/.github/workflows/build_documentation.yml
--- a/.github/workflows/build_documentation.yml
+++ b/.github/workflows/build_documentation.yml
@@ -12,9 +12,38 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-
-    - name: Execute script to build our documentation and update pages
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: "docs/buildDocs.sh"
-      shell: bash
+    # Standard drop-in approach that should work for most people.
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        docs-folder: "docs/"
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: DocumentationHTML
+        path: docs/_build/html/
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      run: |
+        git config --global user.name "${GITHUB_ACTOR}"
+        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+        git init
+        git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
+        git checkout -b gh-pages
+        
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+                
+        git add .
+        git commit -m "Update documentation." -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+        git push deploy gh-pages --force
+#    - name: Push changes
+#      uses: ad-m/github-push-action@master
+#      with:
+#        branch: gh-pages
+#        directory: gh-pages
+#        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
